# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "hanami-api"
gem "jwt"
gem "puma"

group :development, :test do
  gem "rubocop"
  gem "solargraph"
end
